# Generated by Django 5.0.7 on 2024-07-17 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("service_rest", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="appointment",
            name="status",
            field=models.BooleanField(
                choices=[
                    ("created", "Created"),
                    ("canceled", "Cancaled"),
                    ("finished", "Finished"),
                ],
                default="created",
            ),
        ),
    ]
