# Generated by Django 5.0.7 on 2024-07-17 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("service_rest", "0002_alter_appointment_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="appointment",
            name="status",
            field=models.CharField(
                choices=[
                    ("created", "Created"),
                    ("canceled", "Cancaled"),
                    ("finished", "Finished"),
                ],
                default="created",
                max_length=10,
            ),
        ),
    ]
