# Generated by Django 5.0.7 on 2024-07-18 17:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("service_rest", "0004_alter_appointment_technician"),
    ]

    operations = [
        migrations.AlterField(
            model_name="appointment",
            name="technician",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="Technician",
                to="service_rest.technician",
            ),
        ),
    ]
